language: ruby
rvm:
  - ruby-2.6.3

addons:
  apt:
    packages:
      - fonts-ipafont

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp config/initializers/hosting.rb.example config/initializers/hosting.rb

script:
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake spec
